{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "461cc990",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: duckdb in ./.venv/lib/python3.13/site-packages (1.4.1)\n"
     ]
    }
   ],
   "source": [
    "!pip install duckdb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "81146326",
   "metadata": {},
   "outputs": [
    {
     "ename": "HTTPException",
     "evalue": "HTTP Error: HTTP GET error reading 's3://silver/taxi_data.parquet/silver/?encoding-type=url&list-type=2&prefix=taxi_data.parquet%2F' in region '' (HTTP 403 Forbidden)\n\nAuthentication Failure - this is usually caused by invalid or missing credentials.\n* Credentials are provided, but they did not work.\n* See https://duckdb.org/docs/stable/extensions/httpfs/s3api.html\n\nLINE 3:     SELECT * FROM read_parquet('s3://silver/taxi_data.parquet/*.parquet') \n                          ^",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mHTTPException\u001b[39m                             Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[16]\u001b[39m\u001b[32m, line 17\u001b[39m\n\u001b[32m      8\u001b[39m con.execute(\u001b[33mf\u001b[39m\u001b[33m\"\"\"\u001b[39m\n\u001b[32m      9\u001b[39m \u001b[33m    SET s3_endpoint=\u001b[39m\u001b[33m'\u001b[39m\u001b[33mlocalhost:9000\u001b[39m\u001b[33m'\u001b[39m\u001b[33m;\u001b[39m\n\u001b[32m     10\u001b[39m \u001b[33m    SET s3_access_key_id=\u001b[39m\u001b[33m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mos.getenv(\u001b[33m'\u001b[39m\u001b[33mMINIO_ROOT_USER\u001b[39m\u001b[33m'\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m'\u001b[39m\u001b[33m;\u001b[39m\n\u001b[32m   (...)\u001b[39m\u001b[32m     13\u001b[39m \u001b[33m    SET s3_url_style=\u001b[39m\u001b[33m'\u001b[39m\u001b[33mpath\u001b[39m\u001b[33m'\u001b[39m\u001b[33m;\u001b[39m\n\u001b[32m     14\u001b[39m \u001b[33m\"\"\"\u001b[39m)\n\u001b[32m     16\u001b[39m \u001b[38;5;66;03m# Queries here!\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m17\u001b[39m df = \u001b[43mcon\u001b[49m\u001b[43m.\u001b[49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\"\"\u001b[39;49m\n\u001b[32m     18\u001b[39m \n\u001b[32m     19\u001b[39m \u001b[33;43m    SELECT * FROM read_parquet(\u001b[39;49m\u001b[33;43m'\u001b[39;49m\u001b[33;43ms3://silver/taxi_data.parquet/*.parquet\u001b[39;49m\u001b[33;43m'\u001b[39;49m\u001b[33;43m) \u001b[39;49m\n\u001b[32m     20\u001b[39m \u001b[33;43m    LIMIT 10;\u001b[39;49m\n\u001b[32m     21\u001b[39m \u001b[33;43m\"\"\"\u001b[39;49m\u001b[43m)\u001b[49m.df()\n\u001b[32m     23\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mNumber of rows: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mlen\u001b[39m(df)\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m     24\u001b[39m df.head()\n",
      "\u001b[31mHTTPException\u001b[39m: HTTP Error: HTTP GET error reading 's3://silver/taxi_data.parquet/silver/?encoding-type=url&list-type=2&prefix=taxi_data.parquet%2F' in region '' (HTTP 403 Forbidden)\n\nAuthentication Failure - this is usually caused by invalid or missing credentials.\n* Credentials are provided, but they did not work.\n* See https://duckdb.org/docs/stable/extensions/httpfs/s3api.html\n\nLINE 3:     SELECT * FROM read_parquet('s3://silver/taxi_data.parquet/*.parquet') \n                          ^"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 339, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py\", line 345, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/bogdan/code/etl-pipeline/.venv/lib/python3.13/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import duckdb\n",
    "\n",
    "# That's it! No server, no container needed\n",
    "con = duckdb.connect()\n",
    "\n",
    "# Configure to connect to your MinIO\n",
    "con.execute(f\"\"\"\n",
    "    SET s3_endpoint='localhost:9000';\n",
    "    SET s3_access_key_id='{os.getenv('MINIO_ROOT_USER')}';\n",
    "    SET s3_secret_access_key='{os.getenv('MINIO_ROOT_PASSWORD')}';\n",
    "    SET s3_use_ssl=false;\n",
    "    SET s3_url_style='path';\n",
    "\"\"\")\n",
    "\n",
    "# Queries here!\n",
    "df = con.execute(\"\"\"\n",
    "                 \n",
    "    SELECT * FROM read_parquet('s3://silver/taxi_data.parquet/*.parquet') \n",
    "    LIMIT 10;\n",
    "\"\"\").df()\n",
    "\n",
    "print(f\"Number of rows: {len(df)}\")\n",
    "df.head()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
